apiVersion: v1
kind: Service

metadata:
  name: event-manager-service

spec:
  type: NodePort

  selector:
    app: event-manager

  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30080